CREATE TABLE smssend (
     Id BIGINT NOT NULL,
     ANumber VARCHAR(255) NOT NULL,
     BNumber VARCHAR(255) NOT NULL,
     Text VARCHAR(255) NOT NULL,
);

CREATE SEQUENCE SMSSEND_SEQ START WITH 1 INCREMENT BY 1;